name: API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish ./Api/UrlShortener.Api.csproj -c Release -o ./output
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-artifact
        path: ./output

  deploy-Dev:
          runs-on: ubuntu-latest
          needs: build
          environment: dev
      
          steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: dotnet-artifact
              path: .
      
          - name: Deploy to Azure Web App
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ vars.API_RESOURCE_NAME }}
              slot-name: 'production'
              publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
              package: ./output
      