name: Azure-Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:  #manual trigger

permissions:
  contents: read  # Allow read access to the repository contents
  id-token: write  # Allow write access to the ID token

jobs:
 deploy-dev:
   runs-on: ubuntu-latest
   environment: dev
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Azure CLI Login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Create Resource Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ vars.AZURE_RESOURCE_GROUP }} --location ${{ vars.AZURE_LOCATION }}
            echo "Resource group created successfully."

      - name: Deploy Infrastructure
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "🚀 Deploying Bicep template..."
            az deployment group create \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --template-file ./Infrastructure/main.bicep